In [28]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [29]:
data=pd.read_csv("unimelb_training.csv",low_memory=False)
test=pd.read_csv("unimelb_test.csv")

In [30]:
data.shape

(8708, 252)

In [31]:
data.head()

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Faculty.No..15,With.PHD.15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Unnamed: 251
0,1,1,NaN,NaN,A,8/11/05,280199.0,100.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,2B,10A,B,11/11/05,280103.0,30.0,280106.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,29A,10B,A,14/11/05,321004.0,60.0,321216.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,40D,10B,C,15/11/05,270602.0,50.0,320602.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,59C,10A,A,16/11/05,260500.0,34.0,280000.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8708 entries, 0 to 8707
Columns: 252 entries, Grant.Application.ID to Unnamed: 251
dtypes: float64(180), int64(2), object(70)
memory usage: 16.7+ MB

In [33]:
data.tail()

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Faculty.No..15,With.PHD.15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Unnamed: 251
8703,8704,1,21A,50A,A,23/12/08,321028.0,100.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8704,8705,1,21A,50A,A,23/12/08,340299.0,50.0,390114.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8705,8706,0,137A,30B,NaN,24/12/08,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8706,8707,1,21A,50A,A,24/12/08,280210.0,40.0,239901.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8707,8708,1,21A,50A,A,24/12/08,321012.0,70.0,321005.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
data.describe()

,Grant.Application.ID,Grant.Status,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,RFCD.Code.3,RFCD.Percentage.3,RFCD.Code.4,RFCD.Percentage.4,...,Dept.No..15,Faculty.No..15,With.PHD.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15,C.15,Unnamed: 251
count,8708.000000,8708.000000,8074.000000,8074.000000,8074.000000,8074.000000,8074.000000,8074.000000,8074.000000,8074.000000,...,2.0,2.0,0.0,2.0,2.0,2.00000,2.0,2.0,0.0,0.0
mean,4354.500000,0.458429,314625.121006,75.005251,158842.523161,17.595281,92956.217736,6.883986,6551.696309,0.406490,...,3048.0,31.0,NaN,1.0,0.0,11.50000,3.0,2.0,NaN,NaN
std,2513.927405,0.498297,51817.235580,26.836228,160685.895040,19.438356,146607.359501,11.806640,44953.214321,3.004969,...,0.0,0.0,NaN,0.0,0.0,2.12132,0.0,0.0,NaN,NaN
min,1.000000,0.000000,210000.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3048.0,31.0,NaN,1.0,0.0,10.00000,3.0,2.0,NaN,NaN
25%,2177.750000,0.000000,280204.000000,50.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,3048.0,31.0,NaN,1.0,0.0,10.75000,3.0,2.0,NaN,NaN
50%,4354.500000,0.000000,320704.000000,80.000000,230202.000000,10.000000,0.000000,0.000000,0.000000,0.000000,...,3048.0,31.0,NaN,1.0,0.0,11.50000,3.0,2.0,NaN,NaN
75%,6531.250000,1.000000,321202.000000,100.000000,320700.750000,30.000000,270105.000000,10.000000,0.000000,0.000000,...,3048.0,31.0,NaN,1.0,0.0,12.25000,3.0,2.0,NaN,NaN
max,8708.000000,1.000000,999999.000000,100.000000,440209.000000,90.000000,440207.000000,80.000000,440202.000000,70.000000,...,3048.0,31.0,NaN,1.0,0.0,13.00000,3.0,2.0,NaN,NaN

In [35]:
total=data.isnull().sum().sort_values(ascending=False)
total

Dept.No..5              8708
B.14                    8708
A.14                    8708
A..14                   8708
With.PHD.14             8708
                        ...
B.1                      523
Role.1                    98
Start.date                 0
Grant.Status               0
Grant.Application.ID       0
Length: 252, dtype: int64

In [36]:
percent = (data.isnull().sum() / data.isnull().count() * 100).sort_values(ascending = False)
missing_train_data = pd.concat([total, percent], axis = 1, keys = ['Total', 'Percent'])
missing_train_data.head(50)

                                         Total     Percent
Dept.No..5                                8708  100.000000
B.14                                      8708  100.000000
A.14                                      8708  100.000000
A..14                                     8708  100.000000
With.PHD.14                               8708  100.000000
No..of.Years.in.Uni.at.Time.of.Grant.14   8708  100.000000
Number.of.Successful.Grant.14             8708  100.000000
Unnamed: 251                              8708  100.000000
Home.Language.12                          8708  100.000000
Home.Language.13                          8708  100.000000
Role.14                                   8708  100.000000
C.15                                      8708  100.000000
With.PHD.15                               8708  100.000000
Home.Language.15                          8708  100.000000
Person.ID.14                              8708  100.000000
C.14                                      8708  100.000000
Number.of.Unsuccessful.Grant.14           8708  100.000000
Dept.No..14                               8708  100.000000
Home.Language.11                          8708  100.000000
Faculty.No..11                            8708  100.000000
Home.Language.14                          8708  100.000000
Faculty.No..14                            8708  100.000000
B.15                                      8706   99.977033
Home.Language.8                           8706   99.977033
Home.Language.9                           8706   99.977033
Home.Language.7                           8706   99.977033
Number.of.Unsuccessful.Grant.15           8706   99.977033
Dept.No..15                               8706   99.977033
Year.of.Birth.15                          8706   99.977033
Person.ID.15                              8706   99.977033
A..15                                     8706   99.977033
Country.of.Birth.15                       8706   99.977033
Number.of.Successful.Grant.15             8706   99.977033
A.15                                      8706   99.977033
Faculty.No..15                            8706   99.977033
No..of.Years.in.Uni.at.Time.of.Grant.15   8706   99.977033
Year.of.Birth.14                          8705   99.965549
C.13                                      8705   99.965549
Home.Language.10                          8705   99.965549
With.PHD.11                               8705   99.965549
No..of.Years.in.Uni.at.Time.of.Grant.13   8705   99.965549
Country.of.Birth.14                       8705   99.965549
Year.of.Birth.13                          8705   99.965549
Faculty.No..13                            8705   99.965549
B.13                                      8705   99.965549
A..13                                     8705   99.965549
Number.of.Unsuccessful.Grant.13           8705   99.965549
Country.of.Birth.13                       8705   99.965549
Dept.No..13                               8705   99.965549
Person.ID.13                              8705   99.965549

In [37]:
data.dropna(axis = 1, how = 'all')

,Grant.Application.ID,Grant.Status,Sponsor.Code,Grant.Category.Code,Contract.Value.Band...see.note.A,Start.date,RFCD.Code.1,RFCD.Percentage.1,RFCD.Code.2,RFCD.Percentage.2,...,Year.of.Birth.15,Country.of.Birth.15,Dept.No..15,Faculty.No..15,No..of.Years.in.Uni.at.Time.of.Grant.15,Number.of.Successful.Grant.15,Number.of.Unsuccessful.Grant.15,A..15,A.15,B.15
0,1,1,NaN,NaN,A,8/11/05,280199.0,100.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,1,2B,10A,B,11/11/05,280103.0,30.0,280106.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,1,29A,10B,A,14/11/05,321004.0,60.0,321216.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,1,40D,10B,C,15/11/05,270602.0,50.0,320602.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,0,59C,10A,A,16/11/05,260500.0,34.0,280000.0,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8703,8704,1,21A,50A,A,23/12/08,321028.0,100.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8704,8705,1,21A,50A,A,23/12/08,340299.0,50.0,390114.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8705,8706,0,137A,30B,NaN,24/12/08,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8706,8707,1,21A,50A,A,24/12/08,280210.0,40.0,239901.0,40.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8707,8708,1,21A,50A,A,24/12/08,321012.0,70.0,321005.0,30.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
data.dropna(axis=1,thresh=8000,inplace=True)

In [39]:
train_columns=data.columns

In [40]:
test.dropna(axis=1,thresh=8000,inplace=True)

In [43]:
test

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[2176 rows x 0 columns]

In [44]:
data.shape

(8708, 32)

In [45]:
test.shape

(2176, 0)